import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#0f172a" },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
    borderBottom: "2pt solid #0d2d52",
    paddingBottom: 12,
  },
  logo: { width: 56, height: 56, objectFit: "contain" },
  clubInfo: { textAlign: "right", fontSize: 9, color: "#64748b" },
  title: { fontSize: 18, fontWeight: "bold", color: "#0d2d52", marginBottom: 4 },
  subtitle: { fontSize: 10, color: "#64748b", marginBottom: 20 },
  box: { padding: 14, backgroundColor: "#f8fafc", borderRadius: 4, marginBottom: 16 },
  row: { flexDirection: "row", marginBottom: 4 },
  label: { width: 130, color: "#64748b" },
  value: { flex: 1, fontWeight: "bold" },
  amount: { fontSize: 22, fontWeight: "bold", color: "#0d2d52", marginTop: 8 },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    borderTop: "1pt solid #e2e8f0",
    paddingTop: 8,
    fontSize: 8,
    color: "#94a3b8",
    textAlign: "center",
  },
});

export interface DuesInvoicePDFData {
  club: { name: string; address?: string; logoUrl?: string };
  member: { firstName: string; lastName: string; email?: string };
  invoiceNumber: string;
  fiscalYear: string;
  periodLabel: string;
  paymentPlan: string;
  amount: string;
  dueDate: string;
  issuedAt: string;
  locale: string;
}

export function DuesInvoicePDFDocument({ data }: { data: DuesInvoicePDFData }) {
  const isFr = data.locale === "fr";
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <View>
            {data.club.logoUrl ? <Image src={data.club.logoUrl} style={styles.logo} /> : null}
          </View>
          <View style={styles.clubInfo}>
            <Text>{data.club.name}</Text>
            {data.club.address ? <Text>{data.club.address}</Text> : null}
          </View>
        </View>
        <Text style={styles.title}>{isFr ? "FACTURE DE COTISATION" : "DUES INVOICE"}</Text>
        <Text style={styles.subtitle}>
          {data.invoiceNumber} · {isFr ? "Exercice" : "Fiscal year"} {data.fiscalYear}
        </Text>
        <View style={styles.box}>
          <View style={styles.row}>
            <Text style={styles.label}>{isFr ? "Membre" : "Member"}</Text>
            <Text style={styles.value}>
              {data.member.firstName} {data.member.lastName}
            </Text>
          </View>
          {data.member.email ? (
            <View style={styles.row}>
              <Text style={styles.label}>Email</Text>
              <Text style={styles.value}>{data.member.email}</Text>
            </View>
          ) : null}
          <View style={styles.row}>
            <Text style={styles.label}>{isFr ? "Période" : "Period"}</Text>
            <Text style={styles.value}>{data.periodLabel}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{isFr ? "Mode de paiement" : "Payment plan"}</Text>
            <Text style={styles.value}>{data.paymentPlan}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>{isFr ? "Échéance" : "Due date"}</Text>
            <Text style={styles.value}>{data.dueDate}</Text>
          </View>
          <Text style={styles.amount}>{data.amount}</Text>
        </View>
        <Text style={{ fontSize: 9, color: "#64748b" }}>
          {isFr ? "Émis le" : "Issued on"} {data.issuedAt}
        </Text>
        <Text style={styles.footer}>
          {data.club.name} — {isFr ? "Document généré par Rotary Minutes" : "Generated by Rotary Minutes"}
        </Text>
      </Page>
    </Document>
  );
}